spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/therappy
    username: therappy
    password: therappy

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

app:
  crypto:
    aesKeyBase64: "0123456789abcdefghij0123456789VaPupaHantuTP"
  jwt:
    secret: "TudorPopaAFostAici!VaPupaHantu!StucaniiStudios,PoweredByTheBoysStudios"
    ttlSeconds: 900
  refresh:
    ttlSeconds: 1209600

server:
  port: 8080
  tomcat:
    max-swallow-size: 10MB